name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ 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 }}
          template: classic
          base: repositories
#           base: header, activity, community
#           base: header, repositories
          plugin_gists: yes
          plugin_fortune: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
